# Generated by Django 5.0.6 on 2024-12-18 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Les4Fantastiques', '0007_alter_question_created_at_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 18, 10, 37, 14, 571197)),
        ),
    ]
