# Generated by Django 5.0.6 on 2024-12-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Les4Fantastiques', '0013_remove_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
    ]
