# Generated by Django 5.0.6 on 2024-12-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Les4Fantastiques', '0014_remove_question_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
