# Generated by Django 5.0.6 on 2024-12-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Les4Fantastiques', '0015_remove_customuser_email_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
