# Generated by Django 5.0.6 on 2024-12-18 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Les4Fantastiques', '0017_question_created_at_alter_score_best_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 18, 10, 59, 12, 496758)),
        ),
    ]
